[package]
name = "speedreader"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.9", package = "gtk4" }
poppler = "0.5.1"
tokio = "1.41.0"
futures = "0.3.31"
async-std = "1.13.0"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"